### ISSUE TITLE
Adding a comment throws an error when there are dashes in the path

### ISSUE THREAD

**Issue by jhansen81** [WeTeam/WeBlog#52] opened 2014-02-05 01:09 UTC
The duplicate submission code attempts to find a duplicate comment using a fast query.  When the path to the entry is retrieved, if the path has dashes in it, the fast query fails with "End of string expected at position XX".  If you remove the dash from the item names the error goes away.  The dashes just need to be escaped prior to passing the path to the fast query.

**Comment by Sindberg** [comment] 2015-01-22 10:52
The problem is that fast queries need "dashes" "and "or" and a whammy of other stuff escaped. Official documentation here: http://sdn.sitecore.net/upload/sdn5/developer/using%20sitecore%20fast%20query/using%20sitecore%20fast%20query001.pdf

Filtering the Path in DuplicateSubmissionGuard through this method should solve the issue: 
``` C#
public string EscapePath(string path)
{
	string[] joints = Regex.Split(path, "/");
	string output = string.Empty;
	for (int index = 0; index < joints.Length; index++)
	{
		string joint = joints[index];
		if (!string.IsNullOrEmpty(joint))
			output += string.Format("#{0}#", joint);

		if (index != joints.Length - 1)
			output += "/";
	}

	return output;
}
```

Would have made a pull request, but couldn't get the project to build. (AnalycticsManager couldn't be resolved)
Would love a fix for the 2.3 version aswell. ;)

**Comment by vaneeth** [comment] 2015-02-13 10:13
Hi we are using 2.3 version for sitecore 7.0. Is it possible to get this fix(dll) for the mentioned version. We are unable to get the project to build. This is quite urgent now. Any help would be appreciated.

**Comment by jhansen81** [comment] 2015-02-13 13:52
I have a built version of the DLL that utilizes a similar method and has been working on our site (7.1) for the past 8 months.  I'm happy to send it to you.

**Comment by vaneeth** [comment] 2015-02-13 14:08
Thatz great! Please do send it to Vaneeth.robert@activeis.net. Many thanks

**Comment by vaneeth** [comment] 2015-02-16 08:39
Many thanks jhansen81 for the DLL. I am now able to add comments. Thanks once again

**Comment by RickyW80** [comment] 2015-03-05 13:46
Hi jhansen81, 
I have been running into that same problem.  We just recently upgraded our clients site to 7.2 from 6.5 and updated the weblog to 2.3 along the way.  No more submission of comments.  Is there any way I can get a copy of your dll?

**Comment by jhansen81** [comment] 2015-03-05 14:25
I've posted a zip file with the DLL to our website: http://www.singlestoneconsulting.com/~/media/files/SitecoreModulesWeblog.zip.

Hope that helps!

Best,

Jeff

**Comment by RickyW80** [comment] 2015-03-05 14:38
Jeff,
That worked like a charm!  Thank you so much for your help.

Thanks,
Ricky

**Comment by Swati1625** [comment] 2015-08-20 12:03
Hello Jeff,

I am using Sitecore 8 and I am facing same problem. Can you please provide me Weblog dll for Sitecore 8? I tried to use dll which you have provided above but it is not working. Please help me.

Thanks,
Swati Gupta

**Comment by jhansen81** [comment] 2015-08-24 14:56
I haven't made one for 8 yet but I can give it a shot this week.






On Thu, Aug 20, 2015 at 5:03 AM -0700, "Swati1625" <notifications@github.com> wrote:












Hello Jeff,



I am using Sitecore 8 and I am facing same problem. Can you please provide me Weblog dll for Sitecore 8? I tried to use dll which you have provided above but it is not working. Please help me.



Thanks,

Swati Gupta

**Comment by Swati1625** [comment] 2015-08-25 10:36
It will be great help.. Please provide me.

**Comment by Swati1625** [comment] 2015-09-03 12:54
Hello Jeff,

Can you please provide me WeBlog dll for 8?

Thanks,
Swati Gupta

**Comment by adeneys** [comment] 2015-09-18 12:01
This has been fixed in release 2.4

**Closed by adeneys** 2015-09-18 12:01 UTC

**Comment by jhansen81** [comment] 2015-09-18 12:15
Hi Swati,
Please use release 2.4 which contains the fix for this issue.
Thanks,Jeff






On Thu, Sep 3, 2015 at 5:54 AM -0700, "Swati1625" <notifications@github.com> wrote:












Hello Jeff,



Can you please provide me WeBlog dll for 8?



Thanks,

Swati Gupta

**Comment by alpasarupria** [comment] 2016-05-24 13:34
![sitecore](https://cloud.githubusercontent.com/assets/2264224/15505706/39009ee6-21e2-11e6-83ea-ad9a0fbe5714.PNG)
I am this issue , while posting comment on blog . I am using SiteCore 8.0.

Please help.

**Comment by alan-null** [comment] 2016-05-24 14:50
Hi @alpasarupria,
Could you please provide any additional information about that? 
* WeBlog version?
* Are you able to reproduce that ? 
* What are possible steps to reproduce? 
*  Is it an instance installed from release package package or dev build
*  Do you have access to any logs? Could you provide any?

If this is possible, please create separate task for that because it has some history already and I am not sure both issues are related.

**Comment by alpasarupria** [comment] 2016-05-25 04:58
1. I have installed WeBlog 2.4 for Sitecore 8.0
2. Yes, it is reproducible
3. I have just installed the WeBlog Module and Created a placeholder. Used that placeholder on page.While submitting it is giving above error.
4. I have installed package from  [](https://marketplace.sitecore.net/en/Modules/WeBlog.aspx)
5. Yes it is creating 


`Stack Trace: 


[ArgumentNullException: Value cannot be null.
Parameter name: item]
   Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName) +63
   Sitecore.Workflows.Simple.WorkflowProvider.GetWorkflow(Item item) +33
   Sitecore.Modules.WeBlog.Pipelines.CreateComment.WorkflowSubmit.Process(CreateCommentArgs args) +127
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +331
   Sitecore.Modules.WeBlog.Managers.CommentManager.AddCommentToEntry(ID entryId, Comment comment, Language language) +128
   Sitecore.Modules.WeBlog.Layouts.BlogSubmitComment.buttonSaveComment_Click(Object sender, EventArgs e) +675
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11750641
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +150
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6016

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0`


Log File 

`22780 10:28:50 ERROR Exception when executing agent aggregation/automationAggregator
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Sitecore.Analytics.MongoDB
   at Sitecore.Analytics.RangeScheduler.MongoDbRangeMap2.TryLockRange(WorkerHandle worker, DateTime leaseExpiration, RangeHandle& range)
   at Sitecore.Analytics.Core.RangeScheduler.RangeMapWorkScheduler2`1.TryLockRange(WorkScheduler`1& context)
   at Sitecore.Analytics.Core.RangeScheduler.RangeMapWorkScheduler2`1.GetNextRange(WorkScheduler`1& context)
   at Sitecore.Analytics.Core.RangeScheduler.RangeMapWorkScheduler2`1.TryGetNext(TKey& item)
   at Sitecore.Analytics.Automation.Aggregation.AutomationWorkDispatcher.TryGetNext(AutomationWorkItem& workItem)
   at Sitecore.Analytics.Automation.Aggregation.Data.Processing.AggregatorAgent.Execute()
   at Sitecore.Analytics.Core.BackgroundService.Run()
`

Please let me know if further information is required.

**Comment by alan-null** [comment] 2016-05-25 07:10
@alpasarupria Thank you for provided information.
I will take a look on that later. If you could be more precise on 3rd point I would really appreciate that.
I am not sure what should I do to reproduce it.

Create new placeholder in Content Editor
Then Add this placeholder on the layout.aspx?

I did it and everything seems to work. Does it happens both on published content and edit mode as well?

Any information you know might be helpful. I will try to find case based on code analysis anyway. Could you also tell me if comment is created in master database?

**Comment by alpasarupria** [comment] 2016-05-25 09:42
![image](https://cloud.githubusercontent.com/assets/2264224/15535111/8d1fb096-2289-11e6-88ee-b3bf7ec2e193.png)
I have created a layout e.g HomeLayout.Added a placeholder 'SubmitComment ' on the HomeLayout as above. Added a field renderer on HomePage.

**Comment by alan-null** [comment] 2016-05-25 11:47
@alpasarupria Now I understand everything, thank you for the images. It explains a lot.
My guess is that you are trying to use this component on a page that is not a WeBlog Entry page is that correct?

Currently all WeBlog components are restricted to live in a specific context (WeBlog context). It means components have to be used only on blog items.

The fact you see something like `#KEY#` on your view means that something is wrong (in this case SubmitComment rendering was unable to find blog home item).

Is your situation the case I described above?

**Comment by alpasarupria** [comment] 2016-05-25 12:32
Yes i think this is the issue. So where i need to add 'SubmitComment' placeholder?

**Comment by alan-null** [comment] 2016-05-25 12:58
Perhaps it will be good idea for you to create blog using branch item to see how things are connected?
Like I said you cannot use SubmitComment outside of WeBlog root item.

Follow instructions below: (Screenshots are made on 7.5 but everything works the same way)
![image](https://cloud.githubusercontent.com/assets/6848691/15540608/a3a3e2e8-2288-11e6-8c24-c517287299ea.png)

Once you do it, just open Entry in Experience Editor
![image](https://cloud.githubusercontent.com/assets/6848691/15540624/b84a2ac2-2288-11e6-9193-1e5058d5b65a.png)

If I were you I would use this approach and then amend any changes to existing layout if required.

**Comment by alpasarupria** [comment] 2016-05-26 11:40
Thanks for the reply. It really helped a lot. Also,could you please how we add tags in blogs.I am getting categories folder but not tags. Do we need to install any Sitecore module for that.

**Comment by alan-null** [comment] 2016-05-26 14:18
@alpasarupria 
Categories are managed (you will have to create category item before using it).
Tags are not managed and can be added without any additional steps.
To do it, simply open your post and type tags using comma as separator. 
```
sitecore, weblog, technology
```
You can paste content both in Content Editor and Experience Editor:
**Experience Editor**
![image](https://cloud.githubusercontent.com/assets/6848691/15577402/ab9a51a6-235c-11e6-81e5-450df71b8d34.png)

**Content Editor**
![image](https://cloud.githubusercontent.com/assets/6848691/15577424/cb6e877c-235c-11e6-80c2-f2fadde7fe71.png)

When you open your post then you will notice that comma separated tags will be displayed as links. So you can easily find relevant content.
What is more you will also get so called 'tag cloud' with all tags in one place (right side bar)
![image](https://cloud.githubusercontent.com/assets/6848691/15577550/4beedbc2-235d-11e6-8558-cc112ef97b9c.png)

**Comment by alpasarupria** [comment] 2016-06-21 13:14
I am facing one issue . I have a blog in which there is one comment section as mentioned above. Now i also have a search functionality on the top of same page.

When i click on search button then that Blog comment part gets highlighted and says that :Fill mandatory fields.

How can i manage two form posts on the same page.

Please help !!

**Comment by adeneys** [comment] 2016-06-21 23:22
Looks like this is caused by not having the WeBlog controls in it's own validation group to isolate it from other controls on the page. I've created a bug to address this #174.

As a workaround, you should be able to use a validation group on your own controls. A post-back from a button in a different validation group will not trigger validation of controls in other validation groups.

**Comment by alpasarupria** [comment] 2016-06-22 04:56
Thanks , it worked for me.

**Comment by alpasarupria** [comment] 2016-06-23 11:19
I am facing issue in Sitecore presentation details. While clicking on Presentation -->Details, popup appears but edit functionality is not working. Clicking on Edit button does not fire any event. Please help!!

**Comment by adeneys** [comment] 2016-06-26 23:40
I don't believe your issue is related to the issue this issue was raised for (Adding a comment throws an error when there are dashes in the path) and this issue is closed. So please open a new issue.

**Comment by alpasarupria** [comment] 2016-06-27 13:38
ok. Please have a look [here ](https://github.com/WeTeam/WeBlog/issues/175).
