### ISSUE TITLE
content delivery configurations

### ISSUE THREAD

**Issue by sergeizak** [WeTeam/WeBlog#245] opened 2017-04-28 15:54 UTC
Hi, I am trying to install Weblog 2.3 on Sitecore.NET 7.2 (rev. 151021). All is fine in CM. But in CD, I am getting "Could not find configuration node: databases/database[@id='master']" error when I navigate to blog item or when I go to Indexing Manager to build weblog search index. CD is not aware of master database. Everything was published to CD which is a copy of CM minus master database. Can you kindly give me a hint as to what I am doing wrong or missing?

Here are error details

Exception: System.InvalidOperationException
Message: Could not find configuration node: databases/database[@id='master']
Source: Sitecore.Kernel
   at Sitecore.Configuration.Factory.GetConfigNode(String xpath, Boolean assert)
   at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name, Boolean assert)
   at Sitecore.Configuration.Factory.GetDatabase(String name)
   at Sitecore.ContentSearch.Maintenance.Strategies.SynchronousStrategy..ctor(String database)

**Comment by adeneys** [comment] 2017-08-17 11:25
That stack trace indicates you may be using the `syncMaster` update strategy in one of your content search indexes, which won't work as you state, because you don't have a master DB available on that server. If you're installing WeBlog 2.3, then that version didn't use ContentSearch, but used the older Sitecore.Search instead. So it's unlikely this issue is related to WeBlog.

**Comment by e-smith** [comment] 2017-10-24 18:16
Just incase anyone runs into this issue again; the problem is that the package should not be installed on the CD servers. Only install the package on the CM server.

**Comment by adeneys** [comment] 2019-12-28 13:13
Closing as the above comments indicate the issue was resolved.

**Closed by adeneys** 2019-12-28 13:13 UTC
